#!/bin/bash
ps cax | grep node > /dev/null
if [ $? -eq 0 ]; then
  echo "Process is running." >/dev/null 2>&1
else
  echo "Process is not running."
  PATH=/home/h9tlmlxl248p/.nvm/versions/node/v11.15.0/bin:$PATH
  cd /home/h9tlmlxl248p/lotterybackend
  pm2 start /home/h9tlmlxl248p/lotterybackend/index.js
fi

